config/routes.rb
Rails.application.routes.draw do
  resources :agreements

   root 'agreements#index'

end

app/models/agreement.rb
class Agreement < ActiveRecord::Base
end

app/controllers/agreements_controller.rb
class AgreementsController < ApplicationController
  before_action :set_agreement, only: [:show, :edit, :update, :destroy]

  # GET /agreements
  # GET /agreements.json
  def index
    @agreements = Agreement.all
  end

  # GET /agreements/1
  # GET /agreements/1.json
  def show
  end

  # GET /agreements/new
  def new
    @agreement = Agreement.new
  end

  # GET /agreements/1/edit
  def edit
  end

  # POST /agreements
  # POST /agreements.json
  def create
    @agreement = Agreement.new(agreement_params)

    respond_to do |format|
      if @agreement.save
        format.html { redirect_to @agreement, notice: 'Agreement was successfully created.' }
        format.json { render :show, status: :created, location: @agreement }
      else
        format.html { render :new }
        format.json { render json: @agreement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agreements/1
  # PATCH/PUT /agreements/1.json
  def update
    respond_to do |format|
      if @agreement.update(agreement_params)
        format.html { redirect_to @agreement, notice: 'Agreement was successfully updated.' }
        format.json { render :show, status: :ok, location: @agreement }
      else
        format.html { render :edit }
        format.json { render json: @agreement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agreements/1
  # DELETE /agreements/1.json
  def destroy
    @agreement.destroy
    respond_to do |format|
      format.html { redirect_to agreements_url, notice: 'Agreement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agreement
      @agreement = Agreement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agreement_params
      params.require(:agreement).permit(:name, :signature, :date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/agreements_helper.rb
module AgreementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agreements/_form.html.erb
<%= form_for @agreement, html: { class: "sigPad" } do |f| %>
  <% if @agreement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agreement.errors.count, "error") %> prohibited this agreement from being saved:</h2>

      <ul>
      <% @agreement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <input type="text" data-provide='datepicker' >
  </div>
  <div class="field">
    <%= f.text_area :name, :class => 'ckeditor' %>
  </div>
  <h5>User Agreement</h5>
  <p>By signing this agreement, you promise to be a great person.</p>
  <div class="sig sigWrapper">
    <div class="typed"></div>
    <canvas class="pad" width="298" height="55"></canvas>
    <%= f.hidden_field :signature, class: "output" %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agreements/edit.html.erb
<h1>Editing Agreement</h1>

<%= render 'form' %>

<%= link_to 'Show', @agreement %> |
<%= link_to 'Back', agreements_path %>

app/views/agreements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Agreements</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Signature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agreements.each do |agreement| %>
      <tr>
        <td><%= sanitize agreement.name %></td>
        <td><%= agreement.signature %></td>
        <td><%= link_to 'Show', agreement %></td>
        <td><%= link_to 'Edit', edit_agreement_path(agreement) %></td>
        <td><%= link_to 'Destroy', agreement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agreement', new_agreement_path %>

app/views/agreements/new.html.erb
<h1>New Agreement</h1>

<%= render 'form' %>

<%= link_to 'Back', agreements_path %>

app/views/agreements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= sanitize @agreement.name %>
</p>

<p>
  <strong>Signature:</strong>
  <%= @agreement.signature %>
</p>

<%= link_to 'Edit', edit_agreement_path(@agreement) %> |
<%= link_to 'Back', agreements_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Signpad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>